export const erc20MetadataAbi = [
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint8" }],
  },
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "string" }],
  },
] as const;

export const erc20BalanceOfAbi = [
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
] as const;

export const priceOracleAbi = [
  {
    type: "function",
    name: "getPrice",
    stateMutability: "view",
    inputs: [{ name: "asset", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "feeds",
    stateMutability: "view",
    inputs: [{ name: "asset", type: "address" }],
    outputs: [
      { name: "feed", type: "address" },
      { name: "maxAge", type: "uint48" },
      { name: "enabled", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "aliases",
    stateMutability: "view",
    inputs: [{ name: "asset", type: "address" }],
    outputs: [{ type: "address" }],
  },
] as const;

export const marketConfigAbi = [
  {
    type: "function",
    name: "debtAsset",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "priceOracle",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "closeFactorBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "minBorrowAmount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "minDebtAmount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "debtCap",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "lpDepositPaused",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "lpWithdrawPaused",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "collateralDepositPaused",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "collateralWithdrawPaused",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "borrowPaused",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "liquidationPaused",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "rateModel",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "baseRateBps", type: "uint16" },
      { name: "kinkUtilizationBps", type: "uint16" },
      { name: "slope1Bps", type: "uint16" },
      { name: "slope2Bps", type: "uint16" },
      { name: "minRateBps", type: "uint16" },
      { name: "maxRateBps", type: "uint16" },
    ],
  },
  {
    type: "function",
    name: "getCollateralAssets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address[]" }],
  },
  {
    type: "function",
    name: "getCollateralConfig",
    stateMutability: "view",
    inputs: [{ name: "asset", type: "address" }],
    outputs: [
      {
        components: [
          { name: "borrowLtvBps", type: "uint16" },
          { name: "liquidationThresholdBps", type: "uint16" },
          { name: "liquidationBonusBps", type: "uint16" },
          { name: "supplyCap", type: "uint256" },
          { name: "valueCapUsd", type: "uint256" },
          { name: "enabled", type: "bool" },
        ],
        type: "tuple",
      },
    ],
  },
] as const;

export const debtPoolAbi = [
  {
    type: "function",
    name: "ASSET",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "marketConfig",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "walletRegistry",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "treasuryFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "treasuryFeeRecipient",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "totalAssets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "availableLiquidity",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "totalDebtAssets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "totalShares",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "previewDeposit",
    stateMutability: "view",
    inputs: [{ name: "assets", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "previewWithdraw",
    stateMutability: "view",
    inputs: [{ name: "shares", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "utilizationBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "currentBorrowRateBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "liquidityIndex",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "borrowIndex",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "lastAccruedAt",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint64" }],
  },
  {
    type: "event",
    name: "Deposited",
    inputs: [
      { indexed: true, name: "account", type: "address" },
      { indexed: false, name: "assets", type: "uint256" },
      { indexed: false, name: "shares", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Withdrawn",
    inputs: [
      { indexed: true, name: "account", type: "address" },
      { indexed: false, name: "assets", type: "uint256" },
      { indexed: false, name: "shares", type: "uint256" },
    ],
  },
] as const;

export const vaultManagerAbi = [
  {
    type: "function",
    name: "marketConfig",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "liquidityPool",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "debtAsset",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "walletRegistry",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "nextVaultId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "vaults",
    stateMutability: "view",
    inputs: [{ name: "vaultId", type: "uint256" }],
    outputs: [
      { name: "owner", type: "address" },
      { name: "normalizedDebt", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "collateralBalances",
    stateMutability: "view",
    inputs: [{ name: "vaultId", type: "uint256" }, { name: "asset", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "vaultOperators",
    stateMutability: "view",
    inputs: [{ name: "vaultId", type: "uint256" }, { name: "operator", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "getVaultCollateralAssets",
    stateMutability: "view",
    inputs: [{ name: "vaultId", type: "uint256" }],
    outputs: [{ type: "address[]" }],
  },
  {
    type: "function",
    name: "debtOf",
    stateMutability: "view",
    inputs: [{ name: "vaultId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "collateralValueUsd",
    stateMutability: "view",
    inputs: [{ name: "vaultId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "borrowCapacityUsd",
    stateMutability: "view",
    inputs: [{ name: "vaultId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "liquidationCapacityUsd",
    stateMutability: "view",
    inputs: [{ name: "vaultId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "debtValueUsd",
    stateMutability: "view",
    inputs: [{ name: "vaultId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "healthFactor",
    stateMutability: "view",
    inputs: [{ name: "vaultId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "currentBorrowRateBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "openVault",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "setVaultOperator",
    stateMutability: "nonpayable",
    inputs: [
      { name: "vaultId", type: "uint256" },
      { name: "operator", type: "address" },
      { name: "allowed", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "depositCollateral",
    stateMutability: "nonpayable",
    inputs: [
      { name: "vaultId", type: "uint256" },
      { name: "asset", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "borrow",
    stateMutability: "nonpayable",
    inputs: [
      { name: "vaultId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "receiver", type: "address" },
    ],
    outputs: [
      { name: "normalizedDebtAdded", type: "uint256" },
      { name: "borrowRateBps", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "VaultOpened",
    inputs: [
      { indexed: true, name: "vaultId", type: "uint256" },
      { indexed: true, name: "owner", type: "address" },
    ],
  },
  {
    type: "event",
    name: "VaultOperatorUpdated",
    inputs: [
      { indexed: true, name: "vaultId", type: "uint256" },
      { indexed: true, name: "operator", type: "address" },
      { indexed: false, name: "allowed", type: "bool" },
    ],
  },
  {
    type: "event",
    name: "CollateralDeposited",
    inputs: [
      { indexed: true, name: "vaultId", type: "uint256" },
      { indexed: true, name: "asset", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "CollateralWithdrawn",
    inputs: [
      { indexed: true, name: "vaultId", type: "uint256" },
      { indexed: true, name: "asset", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "to", type: "address" },
    ],
  },
  {
    type: "event",
    name: "Borrowed",
    inputs: [
      { indexed: true, name: "vaultId", type: "uint256" },
      { indexed: true, name: "owner", type: "address" },
      { indexed: true, name: "receiver", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "normalizedDebtAdded", type: "uint256" },
      { indexed: false, name: "borrowRateBps", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Repaid",
    inputs: [
      { indexed: true, name: "vaultId", type: "uint256" },
      { indexed: true, name: "payer", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "normalizedDebtRepaid", type: "uint256" },
      { indexed: false, name: "remainingDebt", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Liquidated",
    inputs: [
      { indexed: true, name: "vaultId", type: "uint256" },
      { indexed: true, name: "liquidator", type: "address" },
      { indexed: true, name: "collateralAsset", type: "address" },
      { indexed: false, name: "repaidDebt", type: "uint256" },
      { indexed: false, name: "normalizedDebtRepaid", type: "uint256" },
      { indexed: false, name: "seizedCollateral", type: "uint256" },
      { indexed: false, name: "remainingDebt", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "BadDebtResolved",
    inputs: [
      { indexed: true, name: "vaultId", type: "uint256" },
      { indexed: true, name: "resolver", type: "address" },
      { indexed: true, name: "collateralReceiver", type: "address" },
      { indexed: false, name: "writtenOffDebt", type: "uint256" },
      { indexed: false, name: "normalizedDebtWrittenOff", type: "uint256" },
    ],
  },
] as const;
